#version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      #- ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/kk/www/pumpfun/game/youtd2/youtd2-godot/build/web:/var/www/html
      #- ./logs/nginx:/var/log/nginx
      - /Users/kk/www/docker/etc/nginx/ssl:/var/cert
      #- ${FRONTROOT}:/var/www/html/frontend
    cap_add:
      - ALL
    #command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
    networks:
      - server

networks:
  server:
    driver: bridge
